name: 🚢 Create Release GitHub

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: 📦 Fetch develop branch
        run: git fetch origin develop

      - name: 🏗️ Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: 🏗️ Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 🔧 Install dependencies
        run: npm i

      - name: 📄 Get package.json version
        run: echo "APP_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: 🚀 Build APK
        run: eas build -p android --profile preview-test --non-interactive

      - name: 📥 Get APK download URL
        run: |
          BUILD_ID=$(eas build:list | awk 'NR==3 {print $1}')
          DOWNLOAD_URL=$(eas build:view $BUILD_ID | awk '/^Artifact/ {print $2}')
          echo "DOWNLOAD_URL=$DOWNLOAD_URL" >> $GITHUB_ENV
   
      - name: 📥 Download APK
        run: curl -L -o Go4Launch-${{ env.APP_VERSION }}.apk $DOWNLOAD_URL  
        
      - name: ✅ Verify APK size
        run: |
          FILE_SIZE_BYTES=$(stat -c %s Go4Launch-${{ env.APP_VERSION }}.apk)
          FILE_SIZE_MB=$(echo "$FILE_SIZE_BYTES / 1048576" | bc -l)
          MINIMUM_SIZE_MB=15
          if [ "$(echo "$FILE_SIZE_MB < $MINIMUM_SIZE_MB" | bc -l)" -eq 1 ]; then
            echo "❌ APK size is too small ($FILE_SIZE_MB MB)."
          else
            echo "✅ APK size is valid ($FILE_SIZE_MB MB)."
          fi

      - name: 🛠️ Install Fastlane
        run: sudo gem install fastlane     

      - name: 📝 Generate changelog
        run: |
          git checkout develop
          fastlane run changelog_from_git_commits \
            between_last_tag:true \
            pretty:"- %s ~[%h](https://github.com/ivan-cavero/Go4Launch/commit/%H)~" \
            output_file:"changelog.txt"
     
      - name: 🏷️ Create Release GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: '*.apk'
          body_path: changelog.txt
          tag_name: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        
