name: Create Release GitHub

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i

      - name: Install eas-cli
        run: npm global add eas-cli


      - name: Build APK
        run: eas build -p android --profile preview-test --non-interactive
        env:
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}

      - name: Download APK
        run: eas build:download --latest
        env:
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}

      - name: Get package.json version
        run: echo "APP_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Create Release GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: '*.apk'
          body_path: changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate changelog
        run: |
          git fetch --prune --unshallow
          LAST_TAG=$(git describe --abbrev=0 --tags)
          git log --pretty=format:"- %s [%h](https://github.com/ivan-cavero/Go4Launch/commit/%H)" $LAST_TAG..HEAD > changelog.txt
