name: 🚢 Create Release GitHub

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: 📦 Fetch develop branch
        run: git fetch origin develop

      - name: 🏗️ Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: 🏗️ Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 🔧 Install dependencies
        run: npm i

      - name: 📄 Get package.json version
        run: echo "APP_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: 📥 Download APK
        run: |
          BUILD_ID=$(eas build:list | awk 'NR==3 {print $1}')
          DOWNLOAD_URL=$(eas build:view $BUILD_ID | awk '/^Artifact/ {print $2}')
          curl -o Go4Launch-${{ env.APP_VERSION }}.apk $DOWNLOAD_URL

      - name: 📝 Generate changelog
        run: |
          git checkout develop
          LAST_TAG=$(git describe --tags 2>/dev/null || echo "")
          if [ -z "$LAST_TAG" ]; then
            echo "No tags found. Generating changelog from the beginning of the branch."
            git log --pretty=format:"- %s ~[%h](https://github.com/ivan-cavero/Go4Launch/commit/%H)~" origin/develop > changelog.txt
          else
            git log --pretty=format:"- %s ~[%h](https://github.com/ivan-cavero/Go4Launch/commit/%H)~" $LAST_TAG..origin/develop > changelog.txt
          fi      
      - name: 🏷️ Create Release GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: '*.apk'
          body_path: changelog.txt
          tag_name: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: 📄 Set Git identity
        run: |
          git config user.email "ivangonzalezcavero@gmail.com"
          git config user.name "ivan-cavero"

      - name: 🏷️ Create tag for main branch
        run: |
          git checkout main
          git tag -a v${{ env.APP_VERSION }} -m "Version ${{ env.APP_VERSION }}"
          git push --tags
        
      - name: 🏷️ Create tag for develop branch
        run: |
          git checkout develop
          git tag -a v${{ env.APP_VERSION }} -m "Version ${{ env.APP_VERSION }}"
          git push --tags
        
