name: 🚢 Create Release GitHub

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: 📦 Fetch develop branch
        run: git fetch origin develop

      - name: 🏗️ Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: 🏗️ Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 🔧 Install dependencies
        run: npm i

      - name: 🚀 Build APK
        run: eas build -p android --profile preview --non-interactive

      - name: 📥 Get APK download URL
        run: |
          BUILD_ID=$(eas build:list | awk 'NR==3 {print $1}')
          DOWNLOAD_URL=$(eas build:view $BUILD_ID | awk '/^Artifact/ {print $2}')
          echo "DOWNLOAD_URL=$DOWNLOAD_URL" >> $GITHUB_ENV
